const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="mr.poddaaa@gmail.com"
global.location="colombo,sri lanka."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/colombo";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "";
global.website=process.env.GURL || "" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "94768480793";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_05_16_07_27_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNzIsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMjQ1LFxuICAgICAgICAyMjEsXG4gICAgICAgIDE1OCxcbiAgICAgICAgOTksXG4gICAgICAgIDQ2LFxuICAgICAgICAxMixcbiAgICAgICAgMzgsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMTM1LFxuICAgICAgICAxNixcbiAgICAgICAgMTYxLFxuICAgICAgICAzNixcbiAgICAgICAgMjIyLFxuICAgICAgICAxNTksXG4gICAgICAgIDUsXG4gICAgICAgIDE5MSxcbiAgICAgICAgOTcsXG4gICAgICAgIDk2LFxuICAgICAgICAxNTQsXG4gICAgICAgIDQ0LFxuICAgICAgICAyMDMsXG4gICAgICAgIDg3LFxuICAgICAgICA0OCxcbiAgICAgICAgMjE0LFxuICAgICAgICAxNTcsXG4gICAgICAgIDczLFxuICAgICAgICAyNDcsXG4gICAgICAgIDIyLFxuICAgICAgICAxODgsXG4gICAgICAgIDEyMlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxODcsXG4gICAgICAgIDEzMyxcbiAgICAgICAgODQsXG4gICAgICAgIDk4LFxuICAgICAgICAyMzMsXG4gICAgICAgIDIxOSxcbiAgICAgICAgODAsXG4gICAgICAgIDQyLFxuICAgICAgICAxOTAsXG4gICAgICAgIDExOCxcbiAgICAgICAgMTQxLFxuICAgICAgICA1MyxcbiAgICAgICAgMjMxLFxuICAgICAgICAxNTIsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMTk3LFxuICAgICAgICA5MCxcbiAgICAgICAgMjQ0LFxuICAgICAgICAxMjQsXG4gICAgICAgIDgzLFxuICAgICAgICAxODMsXG4gICAgICAgIDI0NixcbiAgICAgICAgMjE4LFxuICAgICAgICA5LFxuICAgICAgICAyNDMsXG4gICAgICAgIDMyLFxuICAgICAgICAxNTksXG4gICAgICAgIDIxMyxcbiAgICAgICAgMjA4LFxuICAgICAgICAxMDIsXG4gICAgICAgIDE0LFxuICAgICAgICA5NFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNDgsXG4gICAgICAgIDIwMyxcbiAgICAgICAgMTY3LFxuICAgICAgICA4NCxcbiAgICAgICAgMTEsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMTI1LFxuICAgICAgICAyNCxcbiAgICAgICAgMTg3LFxuICAgICAgICAxNDQsXG4gICAgICAgIDI2LFxuICAgICAgICAxMjksXG4gICAgICAgIDI4LFxuICAgICAgICAxMzcsXG4gICAgICAgIDE2OCxcbiAgICAgICAgMTU3LFxuICAgICAgICAyMzMsXG4gICAgICAgIDgyLFxuICAgICAgICA5OSxcbiAgICAgICAgMTc1LFxuICAgICAgICAxNzcsXG4gICAgICAgIDIxNixcbiAgICAgICAgMjUwLFxuICAgICAgICA3NyxcbiAgICAgICAgMjU0LFxuICAgICAgICAyMjYsXG4gICAgICAgIDE4NixcbiAgICAgICAgMjU0LFxuICAgICAgICA2NyxcbiAgICAgICAgMjQ5LFxuICAgICAgICA4NyxcbiAgICAgICAgMTA0XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI0OCxcbiAgICAgICAgNjEsXG4gICAgICAgIDIzOCxcbiAgICAgICAgMTgsXG4gICAgICAgIDIwNixcbiAgICAgICAgMTYyLFxuICAgICAgICAxODgsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMjU1LFxuICAgICAgICAxMzksXG4gICAgICAgIDE3MyxcbiAgICAgICAgMTYxLFxuICAgICAgICAxNjEsXG4gICAgICAgIDE4MixcbiAgICAgICAgMjMzLFxuICAgICAgICAxNTEsXG4gICAgICAgIDk5LFxuICAgICAgICAzOSxcbiAgICAgICAgNjcsXG4gICAgICAgIDk2LFxuICAgICAgICAxNDUsXG4gICAgICAgIDIzNyxcbiAgICAgICAgMTkwLFxuICAgICAgICAyMjIsXG4gICAgICAgIDYsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMjUyLFxuICAgICAgICAxNDMsXG4gICAgICAgIDk2LFxuICAgICAgICAxNjUsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMTIxXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMzIsXG4gICAgICAgIDE4MSxcbiAgICAgICAgNCxcbiAgICAgICAgNzUsXG4gICAgICAgIDIzLFxuICAgICAgICA1OCxcbiAgICAgICAgMTAwLFxuICAgICAgICAxNyxcbiAgICAgICAgODUsXG4gICAgICAgIDE1NyxcbiAgICAgICAgODQsXG4gICAgICAgIDExNyxcbiAgICAgICAgODIsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMjE2LFxuICAgICAgICAxNTMsXG4gICAgICAgIDM4LFxuICAgICAgICAxNTgsXG4gICAgICAgIDc1LFxuICAgICAgICAxNjgsXG4gICAgICAgIDEyOSxcbiAgICAgICAgMjI0LFxuICAgICAgICAyMDgsXG4gICAgICAgIDE1NCxcbiAgICAgICAgODYsXG4gICAgICAgIDExNixcbiAgICAgICAgMjQ3LFxuICAgICAgICAxNjAsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMTQ1LFxuICAgICAgICAxNyxcbiAgICAgICAgMTE2XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDY4LFxuICAgICAgICA5LFxuICAgICAgICAxMTYsXG4gICAgICAgIDE4MixcbiAgICAgICAgMTI4LFxuICAgICAgICAyMTcsXG4gICAgICAgIDMzLFxuICAgICAgICA0LFxuICAgICAgICAyNDUsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMjksXG4gICAgICAgIDQ5LFxuICAgICAgICAxMjYsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMTczLFxuICAgICAgICAxMjksXG4gICAgICAgIDM0LFxuICAgICAgICA2OSxcbiAgICAgICAgMTg2LFxuICAgICAgICAxMTUsXG4gICAgICAgIDQ3LFxuICAgICAgICAxMjIsXG4gICAgICAgIDgwLFxuICAgICAgICA3NixcbiAgICAgICAgMjQ0LFxuICAgICAgICAyMTQsXG4gICAgICAgIDI5LFxuICAgICAgICAyMDQsXG4gICAgICAgIDk4LFxuICAgICAgICAyMSxcbiAgICAgICAgMTM1LFxuICAgICAgICAxMjVcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTA0LFxuICAgICAgICAgIDY5LFxuICAgICAgICAgIDI2LFxuICAgICAgICAgIDM3LFxuICAgICAgICAgIDM4LFxuICAgICAgICAgIDM3LFxuICAgICAgICAgIDgwLFxuICAgICAgICAgIDY4LFxuICAgICAgICAgIDgsXG4gICAgICAgICAgMTAsXG4gICAgICAgICAgODEsXG4gICAgICAgICAgMTU3LFxuICAgICAgICAgIDEzOSxcbiAgICAgICAgICAxNjAsXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDE1MCxcbiAgICAgICAgICAxNCxcbiAgICAgICAgICA2OCxcbiAgICAgICAgICAxNSxcbiAgICAgICAgICAxOTUsXG4gICAgICAgICAgNTAsXG4gICAgICAgICAgMTE2LFxuICAgICAgICAgIDIyMCxcbiAgICAgICAgICAxNTgsXG4gICAgICAgICAgMTk5LFxuICAgICAgICAgIDIwOCxcbiAgICAgICAgICAyMjAsXG4gICAgICAgICAgMTEyLFxuICAgICAgICAgIDYxLFxuICAgICAgICAgIDIwNCxcbiAgICAgICAgICA0MSxcbiAgICAgICAgICA5NFxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAyMTQsXG4gICAgICAgICAgMTU3LFxuICAgICAgICAgIDEzOCxcbiAgICAgICAgICAxOTQsXG4gICAgICAgICAgMTIzLFxuICAgICAgICAgIDEzMixcbiAgICAgICAgICA1MCxcbiAgICAgICAgICAxMDcsXG4gICAgICAgICAgMTU1LFxuICAgICAgICAgIDEzMixcbiAgICAgICAgICA4NCxcbiAgICAgICAgICAxODgsXG4gICAgICAgICAgMzIsXG4gICAgICAgICAgMTc3LFxuICAgICAgICAgIDIyNCxcbiAgICAgICAgICAyMjMsXG4gICAgICAgICAgNDYsXG4gICAgICAgICAgNTEsXG4gICAgICAgICAgMTksXG4gICAgICAgICAgMTQ0LFxuICAgICAgICAgIDE1NyxcbiAgICAgICAgICAyMTEsXG4gICAgICAgICAgMTMyLFxuICAgICAgICAgIDE4NixcbiAgICAgICAgICAxODIsXG4gICAgICAgICAgMTA5LFxuICAgICAgICAgIDE3NyxcbiAgICAgICAgICAxNjYsXG4gICAgICAgICAgMTY1LFxuICAgICAgICAgIDEzMixcbiAgICAgICAgICAxMTYsXG4gICAgICAgICAgNzJcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA1MixcbiAgICAgICAgMTk5LFxuICAgICAgICAxMzksXG4gICAgICAgIDM3LFxuICAgICAgICAxNTcsXG4gICAgICAgIDk5LFxuICAgICAgICAyMzUsXG4gICAgICAgIDE2OCxcbiAgICAgICAgMjksXG4gICAgICAgIDcyLFxuICAgICAgICAyMixcbiAgICAgICAgNDcsXG4gICAgICAgIDQ1LFxuICAgICAgICAyMzQsXG4gICAgICAgIDY1LFxuICAgICAgICAxMyxcbiAgICAgICAgMTE3LFxuICAgICAgICA3MSxcbiAgICAgICAgMjE3LFxuICAgICAgICA1MSxcbiAgICAgICAgMTU4LFxuICAgICAgICAzMSxcbiAgICAgICAgMzYsXG4gICAgICAgIDE3OCxcbiAgICAgICAgODQsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMjQ5LFxuICAgICAgICAxNyxcbiAgICAgICAgMjcsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMzQsXG4gICAgICAgIDIzNCxcbiAgICAgICAgNjQsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMjQxLFxuICAgICAgICAzOSxcbiAgICAgICAgMjIwLFxuICAgICAgICAxNjAsXG4gICAgICAgIDIwOSxcbiAgICAgICAgNzksXG4gICAgICAgIDIwOSxcbiAgICAgICAgMjQ3LFxuICAgICAgICA3MixcbiAgICAgICAgMjA0LFxuICAgICAgICAyNDMsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMTQyLFxuICAgICAgICAxMjMsXG4gICAgICAgIDEzOCxcbiAgICAgICAgNjUsXG4gICAgICAgIDUxLFxuICAgICAgICA2NyxcbiAgICAgICAgMjI1LFxuICAgICAgICAxMzMsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTc0LFxuICAgICAgICAyMzgsXG4gICAgICAgIDE0LFxuICAgICAgICAxNjAsXG4gICAgICAgIDE5NSxcbiAgICAgICAgMjI2LFxuICAgICAgICA4NSxcbiAgICAgICAgMTYyLFxuICAgICAgICA1XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAxNDgsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiSVJwbFQ0TXZxcnBGdUN0M3MzVDdCQjBkOVFUNUZYR2IvMklRY3V6dnZ1dz1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW10sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAwLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiQi14UXdQNWZTLTJqZTlTWm93cXlWQVwiLFxuICBcInBob25lSWRcIjogXCJlMTJiMDYyYS00ZDE3LTRiMzYtODQ4Yy02ODY1MTU0YTU3NWJcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTczLFxuICAgICAgNzgsXG4gICAgICAxNjIsXG4gICAgICAxNTMsXG4gICAgICAyNTQsXG4gICAgICAxODYsXG4gICAgICAzNSxcbiAgICAgIDE1OCxcbiAgICAgIDE5MCxcbiAgICAgIDE0NixcbiAgICAgIDU5LFxuICAgICAgMjEsXG4gICAgICAxMzYsXG4gICAgICA2MCxcbiAgICAgIDE2MSxcbiAgICAgIDU5LFxuICAgICAgMjA3LFxuICAgICAgMTg4LFxuICAgICAgMjU1LFxuICAgICAgNzhcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiBmYWxzZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDYxLFxuICAgICAgMTAsXG4gICAgICAyNDYsXG4gICAgICAxNixcbiAgICAgIDExOCxcbiAgICAgIDE5NyxcbiAgICAgIDIwOSxcbiAgICAgIDAsXG4gICAgICAxNjksXG4gICAgICA4OSxcbiAgICAgIDE5LFxuICAgICAgNDYsXG4gICAgICAyMCxcbiAgICAgIDIzMyxcbiAgICAgIDE0OSxcbiAgICAgIDgsXG4gICAgICAxNyxcbiAgICAgIDIyMCxcbiAgICAgIDcyLFxuICAgICAgMTkxXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDTitlOW9VRUVLV0ZrclVHR0FNZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJseEdHOUdicnc1RUFJdFY3eXBWbUpQY0VSb1BIT1hkOHRiM1FYL3ZYQkNvPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcIjB5d0NQU0NnUmlwekY0QnRKeFdvL3ppUit3aGNpeW5xd2JaYzM5dlNGSG16V2E4ekpMYkliWXJHbHlGaXRpOStQcnZ2OW1MSC9teWFLbHc1N3YvSURBPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcImQxaVQ2b0RJNkNTazRUWlBTSnJrM2VMZWZWeHc2MUJiZllsa2wzWENNbCtLMHpCMm5IM0VhZ01yUklackRlc3krNE9YaHdLRFVaamtCd2VjZExkMkFRPT1cIlxuICB9LFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiOTQ3Njg0ODA3OTM6NDJAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjI1MDgxNzkwMjg2NjYzMTo0MkBsaWRcIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjk0NzY4NDgwNzkzOjQyQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMTUxLFxuICAgICAgICAgIDE3LFxuICAgICAgICAgIDEzNCxcbiAgICAgICAgICAyNDQsXG4gICAgICAgICAgMTAyLFxuICAgICAgICAgIDIzNSxcbiAgICAgICAgICAxOTUsXG4gICAgICAgICAgMTQ1LFxuICAgICAgICAgIDAsXG4gICAgICAgICAgMzQsXG4gICAgICAgICAgMjEzLFxuICAgICAgICAgIDEyMyxcbiAgICAgICAgICAyMDIsXG4gICAgICAgICAgMTQ5LFxuICAgICAgICAgIDEwMixcbiAgICAgICAgICAzNixcbiAgICAgICAgICAyNDcsXG4gICAgICAgICAgNCxcbiAgICAgICAgICA3MCxcbiAgICAgICAgICAxMzEsXG4gICAgICAgICAgMTk5LFxuICAgICAgICAgIDU3LFxuICAgICAgICAgIDExOSxcbiAgICAgICAgICAxMjQsXG4gICAgICAgICAgMTgxLFxuICAgICAgICAgIDE4OSxcbiAgICAgICAgICAyMDgsXG4gICAgICAgICAgOTUsXG4gICAgICAgICAgMjUxLFxuICAgICAgICAgIDIxNSxcbiAgICAgICAgICA0LFxuICAgICAgICAgIDQyXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjIwNTczODUsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFBbWxcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUFtbC5qc29uIjogIntcImtleURhdGFcIjpcInkvWElqcVdRUjVxSFEzd0gwdGhsUFhBK1Rld2ZrV1V3azZBTVZ2QkpEeFk9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTA4NjE2NDgyOCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBQW1uLmpzb24iOiAie1wia2V5RGF0YVwiOlwiQUNyY1ZzOTNuSW01U3JXSzl5UEI4aXFDclgzWm5pbHAxalgwS0tsQkZ6MD1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMDg2MTY0ODI5LFwiY3VycmVudEluZGV4XCI6MixcImRldmljZUluZGV4ZXNcIjpbMCwxLDJdfSxcInRpbWVzdGFtcFwiOlwiMTcxODI4ODg1MzQ3OFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUFtby5qc29uIjogIntcImtleURhdGFcIjpcIk0zajNzVlJzZUE5V2VQQ3B5M0dDZEdSbG8vOHF3RnAvb01OVnppZnlJK0E9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTA4NjE2NDgyOSxcImN1cnJlbnRJbmRleFwiOjIsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBQW1wLmpzb24iOiAie1wia2V5RGF0YVwiOlwiQWlFN1YzenY4UXlBQUZrK3hOSkptMGplZUY1YmNUaExuSTRwL2VrRGxNND1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMDg2MTY0ODMwLFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MTk0NTc5NzU4NTVcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFBbXEuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJyUGJSQlJhbUYxVmUrc1JSNWFVdGU4RGY5Ty80SUFEc1RjTmMxQ1RrZFpJPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEwODYxNjQ4MzAsXCJjdXJyZW50SW5kZXhcIjoyLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUFtci5qc29uIjogIntcImtleURhdGFcIjpcInhJV2dPUm1Xc0pEUk96cjNsU3NJR0p1VWFqTzBGaFBPaUxCaUpHaE5Hd1E9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTA4NjE2NDgzMCxcImN1cnJlbnRJbmRleFwiOjQsXCJkZXZpY2VJbmRleGVzXCI6WzAsMSwzXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFBbXMuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJTUHdZcTZxeWhOa0VOdjByTWhoOGwyVmh4OHlxblBMWEE3cmhzQW1TS2ZNPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEwODYxNjQ4MzAsXCJjdXJyZW50SW5kZXhcIjo0LFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUFtdC5qc29uIjogIntcImtleURhdGFcIjpcIlE2WnBPUzZ3aEpNR2x0RnNqc21hWjd5SU5CN2pkbUY3c2Y0bDlEZ05hMk09XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTA4NjE2NDgzMCxcImN1cnJlbnRJbmRleFwiOjQsXCJkZXZpY2VJbmRleGVzXCI6WzBdfSxcInRpbWVzdGFtcFwiOlwiMTcyMTkxNDc2MTE5M1wifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUFtdS5qc29uIjogIntcImtleURhdGFcIjpcImtrK0I4a3FybDFPbUxzYkhvSldXNDVER1NJaVdjR3B6Sk53L3dKUVR3WG89XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTA4NjE2NDgzMSxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBQW12Lmpzb24iOiAie1wia2V5RGF0YVwiOlwiUmU4bEx1dTQwR1RPL2hCdG1LcWh1NmNubmVkUzBXVEF6NEZ5a0FvNWhqUT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMDg2MTY0ODMxLFwiY3VycmVudEluZGV4XCI6MixcImRldmljZUluZGV4ZXNcIjpbMCwyXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjE5MjM3MTAxNjFcIn0iCn0="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "Suhail",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
